export default [
    "And in the end what's more important, being right or being kind?",
    "I have real tricky time hearing people who don't believe in themselves.",
    "Fairytales do not start, nor do they end, in the dark forest. That's something that only shows up smack dab in the middle of a story. But it will all work out.",
    "Sometimes you have to do the right thing, even if you lose.",
    "You know my philosophy with cats, babies, and apologies: you gotta let them come to you.",
    "The belief that I matter, regardless of what I do or don't achieve. Or the belief that we all deserve to be loved, whether we've been hurt or hurt somebody else.",
    "When girl talk turns into girl hug, you know that either means something horrible's happened or absolutely nothing at all.",
    "You know what my favorite thing was about Sir Isaac Newton? He was so down to Earth.",
    "All human beings are opposed to the laugh police.",
    "Well, fellas, if you're looking for a pep talk from me, you're in trouble. 'Cause I'm like Michael Flatley at 11:59 p.m. on St. Patrick's Day, I'm tapped out.",
    "Hey, look, kind of hurts my feelings y'all don't want to spend next weekend with me, if I'm being honest. But I am the strong silent type, so I ain't gonna let you know. But I'm also loud and weak, because I, like all humans, contain multitudes.",
    "I've had more psychotic episodes than Twin Peaks.",
    "Look at it out there. It looks like a Renaissance painting portraying masculine melancholy.",
    "One more person says something that me and Beard don't understand, I'm gonna have one of my son's classic temper tantrums.",
    "I do love a locker room. It smells like potential.",
    "I believe in Communism. Rom-communism, that is. If Tom Hanks and Meg Ryan can go through some heartfelt struggles and still end up happy, then so can we.",
    "I've never been embarrassed about having streaks in my drawers. You know, it's all part of growing up.",
    "Taking on a challenge is a lot like riding a horse, isn't it? If you're comfortable while you're doing it, you're probably doing it wrong.",
    "If that's a joke, I love it. If not, can't wait to unpack that with you later.",
    "If you would have told me that I'd be drinking tea at 3 o'clock every day, about a year ago...I would have punched you in the mouth.",
    "Be honest with me. It's a prank, right? The tea? Like when us tourist folks aren't around, y'all know it tastes like garbage? You don't love it. It's pigeon sweat.",
    "I do [believe in ghosts]. But more importantly, I think they need to believe in themselves. You know?",
    "Back where I'm from, you try to end a game in a tie; well, that might as well be the first sign of the apocalypse.",
    "We're gonna call this drill 'The Exorcist' 'cause it's all about controlling possession.",
    "You know what the happiest animal on Earth is? It's a goldfish. Y'know why? It's got a 10-second memory. Be a goldfish.",
    "If the internet has taught us anything, it's that sometimes it's easier to speak our minds anonymously.",
    "She's got some fences, alright, but you just gotta hop over 'em.",
    "I think I literally have a better understanding of who killed Kennedy than what is offside...It was the mob.",
    "Jamie, I think that you might be so sure that you're one in a million, that sometimes you forget that out there, you're just 1 of 11. And if you just figure out someway to turn that 'me' into 'us'...the sky's the limit for you.",
    "I always feel so bad for the cows, but you gotta do it; otherwise, they get lost. That was a branding joke. If we were in Kansas right now, I'd just be sitting here waiting for you to finish laughing.",
    "For me, success is not about the wins and losses. It's about helping these young fellas be the best versions of themselves on and off the field.",
    "If I didn't have any confidence, I never would've worn pajamas to my prom and ended up in jail the rest of that night.",
    "You two knuckleheads have split our locker room in half. And when it comes to locker rooms, I like 'em just like my mother's bathing suits. I only wanna see 'em in one piece, you hear?",
    "Here's an idea that's gonna help a little or hurt a whole lot. Who needs a drink?",
    "You know how they say that 'youth is wasted on the young'? Well, I say don't let the wisdom of age be wasted on you. I just came up with that. I feel pretty good about it.",
    "Coach Beard's views on romantic relationships are not too dissimilar from his views on cooking steak. You know, you spend any more than five minutes on one — it loses its flavor.",
    "I gotta say, man, sometimes you remind me of my grandma with the channel hopper. You just push all the wrong buttons.",
    "I feel like we fell out of a lucky tree, hit every branch on the way down, ended up in a pool full of cash and Sour Patch Kids.",
    "What I can tell you is that with the exception of the wit and wisdom of Calvin and Hobbes, not much lasts forever.",
    "Sounds to me like someone's trapped inside life's most complicated shape: a love triangle. Second place of course is the \'I just walked in on my mother-in-law changing into her swimsuit\' dodecahedron.",
    "It's just a group of people who care, Roy. Not unlike folks at a hip-hop concert whose hands are not in the air.",
    "Well, as my doctor told me when I got addicted to fettuccine Alfredo, that's a little rich for my blood.",
    "Guys have underestimated me my entire life. And for years, I never understood why. It used to really bother me. But then one day, I was driving my little boy to school, and I saw this quote by Walt Whitman, and it was painted on the wall there. It said, 'Be curious, not judgmental.' I like that.",
    "You beating yourself up is like Woody Allen playing the clarinet. I don't wanna hear it. All right?",
    "Our goal is to go out like Willie Nelson, on a high.",
    "If y'all were really introverts, you would've been quiet as a church mouse. Unless that church was Westboro Baptist. Those turkeys won't shut up.",
    "Divorce is hard. It doesn't matter if you're the one leaving or if...you're the one who got left. It makes folks do crazy things.",
    "I think that if you care about someone and you got a little love in your heart, there ain't nothing you can't get through together.",
    "All right, fellas, you gotta remember, your body is like day-old rice. If it ain't warmed up properly, something real bad could happen.",
    "We all know speed is important. But being able to stop and change directions quickly? Well, that's like Kanye's 808s & Heartbreak. It don't get nearly enough credit.",
    "Ice cream's the best. It's kinda like seeing Billy Joel live. Never disappoints.",
    "If God wanted games to end in a tie, She wouldn't have invented numbers, all right?",
    "The idea behind every trick play is to have chaos rain down upon your opponents and stun them. Much like the lava did to those poor folks in Pompeii.",
    "That's a special young man right there. Got talent for days, works hard, and he's got a jawline like the White Cliffs of Dover. I'm always rootin' for him.",
    "So I've been hearing this phrase y'all got over here that I ain't too crazy about. \'It's the hope that kills you.\' Y'all know that? I disagree, you know? I think it's the lack of hope that comes and gets you. See, I believe in hope. I believe in belief.",
    "Look, we are not playing for a tie. Ain't nobody here gonna kiss their sister...which is an American phrase that I'm now realizing does not exist here, and that's good, 'cause it's creepy, and I hate it myself; I don't know why I said it.",
    "Ain't nobody in this room alone. Let's be sad now. Let's be sad together. And then we can be a gosh-darn goldfish. Onward. Forward.",
    "There's two buttons I never like to hit, alright? And that's 'panic' and 'snooze.'",
    "It's funny to think about the things in your life that can make you cry just knowing that they existed, can then become the same thing that make you cry knowing that they're now gone.",
    "I shouldn't bring an umbrella to a brainstorm.",
    "I've never met someone who doesn't eat sugar. Only heard about 'em, and they all live in this godless place called Santa Monica.",
    "Doing the right thing is never the wrong thing.",
    "You are more mysterious than David Blaine reading a Sue Grafton novel at Area 51.",
    "Boy, I love meeting people's moms. It's like reading an instruction manual as to why they're nuts.",
    "You should do a TED Talk, 'cause right now you're getting a whole heap of 'Ted listen.'",
    "Like I always say, sometimes the best stew is the one you leave sitting on the stove overnight 'cause you fell asleep watching Citizen Kane after too many beers.",
    "You say impossible, but all I hear is 'I'm possible.'",
    "That right there, that's a scone, OK? It's like a muffin, except it sucks all of the spit out of your mouth.",
    "I don't like gossip, but my butt enjoys a little scuttle.",
    "I never know how to react when a grown man beatboxes in front of me.",
    "If the Lasso way is wrong, it's hard to imagine being right.",
    "Sam was more open than the jar of peanut butter on my counter.",
    "Little tip for y'all. Fries are called chips. Chips are called crisps. And bangers aren't great songs, but they do make you feel like dancing because they're so darn tasty.",
    "It's kind of like back in the 80s when 'bad' meant 'good.'",
    "Old people are so wise. They're like tall Yodas.",
    "We don't not care. We care very much. We care about who you are and what you must have been going through. And from now on, you don't have to go through it by yourself.",
    "I hope that either all of us or none of us are judged by the actions of our weakest moments, but rather by the strength we show when and if we're given a second chance.",
    "The truth will set you free, but first it will piss you off.",
    "Even though football is life, football is also death. And sometimes football is football too. But mostly football is life!",
    "He's a wigwam and a teepee - too tense.",
    "I'm cute as a button and I can rhyme my arse off. God, it's no wonder they want to destroy me!",
    "It's like the Dukes of Hazzard over here. Though y'all probably call it the Earls of Risk.",
    "Horticulture, baby!",
    "For some, it's better to follow your gut than pretend to be excited by following someone else's.",
    "I don't think we change per se, as much as we just...learn to accept who we've always been, you know?",
    "Change isn't about trying to be perfect. Perfection sucks. Perfect is boring.",
    "A lot of times the right idea is just sitting behind a couple of the wrong ones.",
    "Don't sell yourself short. If anything, sell yourself tall and get it tailored later.",
    "I know we can't fix every ache inside of us. But I shouldn't have to pretend it's not there, either.",
    "I think things come into our lives to help us get from one place to a better one.",
    "Isn’t the idea of 'never give up' one of them things we always talk about in sports? And shouldn't that apply to people too?",
    "It may not work out how you think it will or how you hope it does. But believe me, it will all work out.",
    "Just listen to your gut, and on the way down to your gut, check in with your heart. Between those two things, they’ll let you know what's what.",
    "Pain is like carbon monoxide. Expressing it to the person who hurt you is like opening a vent, but holding it in will poison you.",
    "You need to stop letting yesterday get in the way of today.",
    "Y'all got to get together and woman up.",
    "I try to love my Dad for who he is and forgive him for who he isn't",
    "What do you have to be sad about? Did one of the Paw Patrol dogs die?",
    "That is the thing about being a parent. Sometimes you lose and...sometimes you win, but most of the time you just tie. All we can do is keep playing.",
    "Y'all got a town here called 'Tooting'?!",
    "Lads, remember, it's just poopeh. Let it flow."
] as const;
